export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_PRODUCT = 'GET_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';

export const PRODUCT_SEARCH = 'PRODUCT_SEARCH';
export const PRODUCT_SEARCH_RESULTS = 'PRODUCT_SEARCH_RESULTS';
